# Generated by Django 3.1 on 2020-08-22 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='duration',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Video duration in ms'),
        ),
        migrations.AlterField(
            model_name='video',
            name='file_extension',
            field=models.CharField(max_length=256, verbose_name='file extension'),
        ),
        migrations.AlterField(
            model_name='video',
            name='file_mime_type',
            field=models.CharField(max_length=256, verbose_name='file mime type'),
        ),
        migrations.AlterField(
            model_name='video',
            name='file_name',
            field=models.CharField(default='', max_length=512, verbose_name='file name'),
        ),
        migrations.AlterField(
            model_name='video',
            name='file_size',
            field=models.PositiveBigIntegerField(default=0, verbose_name='file size in kB'),
        ),
    ]
