# Generated by Django 3.1 on 2020-08-24 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_auto_20200822_1946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='is_active',
            new_name='is_deleted',
        ),
    ]
