# Generated by Django 3.1 on 2020-08-24 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_auto_20200824_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='file_size',
            field=models.PositiveBigIntegerField(default=0, verbose_name='file size in bytes'),
        ),
    ]
