# Generated by Django 3.1 on 2020-08-28 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0002_auto_20200828_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatepart',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='templates.template'),
        ),
    ]
