# Generated by Django 3.1 on 2020-08-24 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutorial',
            old_name='is_active',
            new_name='is_deleted',
        ),
    ]
